services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    platform: ${HOST_PLATFORM}
    build:
      context: ..
      dockerfile: server/dockerfile
    image: palais-freitas:latest
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Your required environment variables (no values set here; use .env or override)
      - MEL_CLOUD_HOME_USERNAME
      - MEL_CLOUD_HOME_PASSWORD
      - TUYA_CLOUD_ACCESS_KEY
      - TUYA_CLOUD_SECRET_KEY
      - HUE_CLOUD_CLIENT_ID
      - HUE_CLOUD_SECRET
      - HUE_CLOUD_BRIDGE_USERNAME
      - APP_DOMAIN_URL
      - APP_HOME_IP
      - DATABASE_URL
      - MY_HOME_ADDRESS_1
      - MY_HOME_ADDRESS_2
      - AUTH_API_KEY_SECRET
      - AUTH_GOOGLE_CLIENT_ID
      - AUTH_GOOGLE_CLIENT_SECRET
      - AUTH_GOOGLE_URL
      - AUTH_CLIENT_BASE="http://localhost:3001
      - AUTH_SET_SECURE_COOKIE
      - AUTH_SET_DOMAIN_COOKIE
      - AUTH_SET_SAME_SITE_COOKIE
      - AUTH_ALWAYS_DISALLOW_THE_IP
      # Useful runtime pointers
      - CONFIG_PATH=/app/config.json
      - PORT=3001
      # Client Env Vars
      - VITE_API_HOSTNAME="http://localhost:3001/api"
      - VITE_APP_ENV="production"
      - VITE_GOOGLE_CLIENT_ID=${AUTH_GOOGLE_CLIENT_ID}
    ports:
      - "3001:3001"

volumes:
  pgdata:

networks:
  default:
    enable_ipv6: true
